arti/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from views import index  #, custommer_View, lista, 
    

from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^index/$', index),
    #url(r'^nuevo$', login_required( custommer_View ),name="custommer_create"),
    # url(r'^nuevo$', CustommerCreate.as_view(),name="custommer_create"),
    # url(r'^lista$', lista,name="custommer_list"),
]
    

custommer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from views import index, custommer_View, lista, custommer_edit, custommer_delete, \
    CustommerView,CustommerCreate, CustommerUpdate, CustommerDelete,ApplicationList,\
    ApplicationCreate, ApplicationUpdate, ApplicationDelete, listado


from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^index$', index),
    #url(r'^nuevo$', login_required( custommer_View ),name="custommer_create"),
    url(r'^nuevo$', CustommerCreate.as_view(),name="custommer_create"),
    url(r'^lista$', lista,name="custommer_list"),
    url(r'^lista_clase', CustommerView.as_view() ,name="custommer_list_class"),
    url(r'^editar/(?P<id_custommer>\d+)/$', custommer_edit,name="custommer_edit"),  
    url(r'^editar/(?P<pk>\d+)/$', CustommerUpdate.as_view(),name="custommer_edit_class"),  
    url(r'^eliminar/(?P<id_custommer>\d+)/$', custommer_delete,name="custommer_delete"),    
    url(r'^eliminar/(?P<pk>\d+)/$', CustommerDelete.as_view(),name="custommer_delete_class"), 

    url(r'^lista_solicitud$', ApplicationList.as_view() ,name="application_list_class"),   
    url(r'^solicitud_nueva$', ApplicationCreate.as_view(),name="application_create"),
    url(r'^solicitud_editar/(?P<pk>\d+)/$', ApplicationUpdate.as_view(),name="application_edit"),
    url(r'^eliminar_solicitud/(?P<pk>\d+)/$', ApplicationDelete.as_view(),name="application_delete_class"), 


    url(r'^listado',listado, name="listado")


]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, password_reset, password_reset_done,\
     password_reset_confirm,  password_reset_complete, logout_then_login

urlpatterns = [
    url(r'^arti/', include('arti.urls', namespace="arti"),name="arti"),

    url(r'^admin/', admin.site.urls),
    url(r'^custommer/', include('custommer.urls', namespace="custommer"),name="custommer"),
    url(r'^users/', include('users.urls')),
    url(r'^accounts/login',login,{'template_name':'index.html'}, name='login'),

    url(r'^/',logout_then_login, name='logout'),
  
    url(r'^logout/',logout_then_login, name='logout'),


    url(r'^registration/password_reset',password_reset,
    {'template_name':'resgistration/password_reset_form.html', 
     'email_template_name':'registration/password_reset_email.html'     }, name='password_reset'),

    url(r'^registration/password_reset_done',password_reset_done,
    {'template_name':'resgistration/password_reset_done.html',     }, name='password_reset_done'),

    url(r'^registration/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',password_reset_confirm,
    {'template_name':'resgistration/password_reset_confirm.html'   }, name='password_reset_confirm'),


    url(r'^registration/done',password_reset_complete,
    {'template_name':'resgistration/password_reset_complete.html',    }, name='password_reset_complete'),




]

custommer/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Custommer(models.Model):
    id = models.AutoField(primary_key=True)
    name= models.CharField(max_length=10)
    edge= models.IntegerField()
    birth= models.DateField()
    document= models.IntegerField()
    email= models.EmailField()

    def __str__(self):
        return '{}'.format(self.name)



class Application(models.Model):
    custommer= models.ForeignKey(Custommer,null=True, blank=True) 
    custommer_code=models.IntegerField()
    reazon=models.CharField(max_length=100)
    

custommer/forms.py
from django.forms import ModelForm
from django import forms
from models import Custommer, Application

class CustommerForms(ModelForm):
    class Meta():
        model=Custommer

        fields=[
            "name",
            "edge",
            "birth",
            "document",
            "email",
        ]

        labels={
            "name"     : "Name",
            "edge"     : "Edge",
            "birth"    : "Birth",
            "document" :"Document",
            "email"    :"Email",

        }

        widgets={
            "name" : forms.TextInput(
                        attrs={
                            'type' : 'text',
                            'class' : 'your_class',
                            'hidden':False,
                            'max_length':100
                        })
                    ,
            "edge" : forms.TextInput(
                        attrs={
                            'type' : 'number',
                            'class' : 'your_class',
                            'hidden':False,
                            'max_length':100
                        })
                    ,
            "birth" : forms.TextInput(
                        attrs={
                            'type' : 'text',
                            'class' : 'your_class',
                            'hidden':False,
                            'max_length':100
                        })
                    ,
            "document" : forms.TextInput(
                        attrs={
                            'type' : 'text',
                            'class' : 'your_class',
                            'hidden':False,
                            'max_length':100
                        })
                    ,
            "email" :  forms.TextInput(
                        attrs={
                            'type' : 'text',
                            'class' : 'your_class',
                            'hidden':False,
                            'max_length':100
                        })
                    ,
        }


class ApplicationForms(ModelForm):
    class Meta():
        model=Application

        fields=[
            
            "custommer_code",
            "reazon",
        ]

        labels={
            "custommer_code" :"Custommer Code",
            "reazon": "Reazon",

        }

        widgets={
            "custommer_code" : forms.Select(attrs={'class':'forms-control'}),
            "reazon" : forms.TextInput(),
        }

custommer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django import forms
from django.views.generic import ListView, CreateView,UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.core import serializers

######
from django.http import HttpResponse, HttpResponseRedirect
from custommer.forms import CustommerForms,ApplicationForms
from models import Custommer, Application


def listado(request):
    lista=serializers.serialize('json',Custommer.objects.all())
    return HttpResponse(lista,content_type='application/json')



# Create your views here.
def index(request):
    #Se renderiza un html harcode
    #return HttpResponse("Index")
    return render(request,'custommer/index.html')



def custommer_View(request):
    if request=="POST":
        form=CustommerForms(request.POST)
        if form.is_valid():
            form.save()
        return reverse_lazy('custommer/custommer_list.html')

    else :
        form=CustommerForms()
        return render(request,'custommer/custommer_form.html', {'form':form})


def lista(request):
    #Se renderiza un html harcode
    #return HttpResponse("Index")
    custommers=None
    contexto=None

    custommers=Custommer.objects.all() 
    contexto= {'custommers':custommers}

    return render(request,'custommer/custommer_list.html', contexto)


def custommer_edit(request, id_custommer):
    custommer=None
    custommer= Custommer.objects.get(id=id_custommer)
    if request.method=='GET':
        form= CustommerForms(instance=custommer )
    else:
        form=CustommerForms(request.POST, instance=custommer)
        if form.is_valid():
            form.save()
        return redirect('/custommer/lista')
    return render(request,'custommer/custommer_form.html', {'form':form} )


def custommer_delete(request, id_custommer):
    custommer=None
    custommer= Custommer.objects.get(id=id_custommer)
    if request.method=='POST':
        custommer.delete()
        return reverse_lazy('custommer/custommer_list.html')
    return   render(request, 'custommer/custommer_delete.html', {'custommer':custommer})




class CustommerView(ListView):
    model= Custommer
    template_name='custommer/custommer_list.html'
    paginate_by=2



class CustommerCreate(CreateView):
    model=Custommer
    form_class=CustommerForms
    template_name='custommer/custommer_form.html'
    success_url=reverse_lazy('custommer:custommer_list')


class CustommerUpdate(UpdateView):
    model=Custommer
    form_class=CustommerForms
    template_name='custommer/custommer_form.html'
    success_url=reverse_lazy('custommer:custommer_list')


class CustommerDelete(DeleteView):
    model=Custommer
    template_name='custommer/custommer_delete_class.html'
    success_url=reverse_lazy('custommer:custommer_list')





class ApplicationList(ListView):
    model= Application
    template_name='application/application_list.html'

class ApplicationCreate(CreateView):
    model=Application
    form_class=ApplicationForms
    second_form_class=CustommerForms
    template_name='application/application_form.html'
    success_url=reverse_lazy('application:application_list')



    def get_context_data(self,**kwargs):
        context=super(ApplicationCreate,self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form']=self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2']=self.second_form_class(self.request.GET)

        return context


    def post(self,request,*args,**kwargs):
        self.object=self.get_object
        form=self.form_class(request.POST)
        form2=self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            application =form.save(commit=False)
            application.custommer=form2.save()
            application.save()
            return HttpResponseRedirect(self.get_succes_url())
        else:
            return self.render_to_response(self.get_context_data(form=form,form2=form2))



class ApplicationUpdate(UpdateView):
    model=Application
    second_model=Custommer
    form_class=ApplicationForms
    second_form_class=CustommerForms
    template_name='custommer/custommer_form.html'
    success_url=reverse_lazy('application:application_list')

    def get_context_data(self,**kwargs):
        context=super(ApplicationCreate,self).get_context_data(**kwargs)
        pk=self.kwargs.get('pk',0)
        application = self.objects.get(id=pk)
        cuatommer= self.second_model.objects.get(id=application.custommer_id)

        if 'form' not in context:
            context['form']=self.form_class()
        if 'form2' not in context:
            context['form2']=self.second_form_class(instance=custommer)
        context['id']=pk
        return context

    def post(self,request,*args,**kwargs):
        self.object=self.get_object
        id_application=kwargs['pk']
        application= self.model.objects.get(id=id_application)
        application= self.second_model.objects.get(id=application.custommer_id)
        form=self.form_class(request.POST, instance=application)
        form2=self.second_form_class(request.POST, instance=custommer)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_succes_url())
        else:
            return HttpResponseRedirect(self.get_succes_url())





class ApplicationDelete(DeleteView):
    model=Application
    template_name='application/applicartion_delete.html'
    success_url=reverse_lazy('application:application_list')

templates/custommer/custommer_delete.html
{%  extends 'base/base.html' %}


{% block content %} 

<form method="POST">
    {% csrf_token  %}
    <h3> Desea eliminar el registro de {{ custommer.name  }}  </h3>
   
    <button  class="btn btn-danger" type="submit">Eliminar</button>
    <a class="btn btn-default"  href="{ % url   'custommer:custommer_list'    % }"   >Cancelar    </a>
</form>

{% endblock%}

templates/custommer/custommer_delete_class.html
{%  extends 'base/base.html' %}


{% block content %} 

<form method="POST">
    {% csrf_token  %}
    <h3> Desea eliminar el registro de {{ object.name  }}  </h3>
   
    <button  class="btn btn-danger" type="submit">Eliminar</button>
    <a class="btn btn-default"  href="{ % url   'custommer:custommer_list'    % }"   >Cancelar    </a>
</form>

{% endblock%}

templates/custommer/custommer_form.html
{%  extends 'base/base.html' %}


{% block content %} 

<form method="POST">
    {% csrf_token  %}
    {{form.as_p}}
    <div>
        

    </div>
    <div>
        
        
    </div>
    <div>
        
        
    </div>
    <button type="submit">Guardar</button>
</form>

{% endblock%}

templates/custommer/custommer_list.html
{%  extends 'base/base.html' %}


{%block content%} 
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">Handle</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
        {%  if  custommers  %}
        {%  for custommer in custommers  %}

        <tr>
                <th scope="row">{{custommer.id}}</th>
                <td>{{custommer.name}}</td>
                <td>{{custommer.document}}</td>
                <td>{{custommer.edge}}</td>
                <td>  <a class="btn btn-primary" href="{% url  'custommer:custommer_edit' custommer.id    %}" >Editar</a> </td>
                <td>  <a class="btn btn-danger" href="{% url 'custommer:custommer_delete' custommer.id  %}" >Borrar</a> </td>

         </tr>

       
        {%  endfor   %}

        {% else  %}

        <tr>
                <th scope="row">No hay registros</th>
                
        </tr>

        {%  endif   %}

     
    </tbody>
  </table>


{% endblock%}

templates/custommer/custommer_list_class.html
{%  extends 'base/base.html' %}


{%block content%} 
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">Handle</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
        {%  if  object_list  %}
        {%  for custommer in object_list  %}

        <tr>
                <th scope="row">1</th>
                <td>{{custommer.name}}</td>
                <td>{{custommer.document}}</td>
                <td>{{custommer.edge}}</td>
                <td>  <a class="btn btn-primary" href="{% url  'custommer:custommer_edit' {custommer.id}      %}" >Editar</a> </td>
                <td>  <a class="btn btn-danger" href="{% url 'custommer:custommer_delete' {custommer.id}  %}" >Borrar</a> </td>

         </tr>

       
        {%  endfor   %}

        {% else  %}

        <tr>
                <th scope="row">No hay registros</th>
                
        </tr>

        {%  endif   %}

     <ul>
       
       <li>
          {% if page_obj.has_previous  %}
          <a href="?page={{page_obj.previous_page_number}}"  >Previous</a>
          {% endif%}
        </li>
        <li>
            {% if page_obj.has_next  %}
            <a href="?page={{page_obj.next_page_number}}"   >Previous</a>
            {% endif%}
          </li>
     </ul>
        


    </tbody>
  </table>


{% endblock%}

templates/custommer/index.html
{%  extends 'base/base.html' %}

{% block content %} 
<div class="row">
    <div class="">
            <h5>
                Contenido del archivo custommer
                
            </h5>
            </div>
        </div>

            
{% endblock%}